### ISSUE TITLE
Solver does not implement signal handling

### ISSUE THREAD

**Issue by daajoe** [vgerber/sat_competition#1]
Your solver does not implement signal handling to the started process tree. This results in the situation that the sat solver (clasp) might still be running even though the benchmark tool or cluster scheduler sent a kill signal to the solver after timeout.
(check with kill -15 mysolver or kill -9 mysolver)

**Comment by vgerber** [comment]
kill -9 == SIGKILL and SIGKILL can't be handled by the program.
https://stackoverflow.com/a/3908710

for calling sigkill use **kill -9 -- -group_process_id** and kill the whole group

**Comment by daajoe** [comment]
Make sure that sigterm works!

**Comment by vgerber** [comment]
Fixed in commit 0b2a56ff629b08b234beda0a58a1055f05165748
